type: set-ilm-policy
name: data-identity-sign-up-policy
policy:
  phases:
    hot:
      actions:
        rollover:
          max_size: 1GB
          max_age: 1d
        set_priority:
          priority: 100
    warm:
      actions:
        readonly: {}
        set_priority:
          priority: 50
---
type: set-template
name: data-identity-sign-up-template
index_patterns:
  - data-identity-sign-up-*
settings:
  number_of_replicas: 1
  number_of_shards: 1
  index:
    lifecycle:
      name: data-identity-sign-up-policy
      rollover_alias: data-identity-sign-up
---
type: put-index-settings
index: data-identity-sign-up-000001
aliases:
  data-identity-sign-up:
    is_write_index: true
